mybatis.mapper-locations: classpath*:/mybatis/*Mapper.xml

spring:
  thymeleaf:
    prefix: classpath:/templates/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hnis??useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10